### ISSUE TITLE
Volume Down and Power Button Not Working

### ISSUE THREAD

**Issue by ghost** [psndna88/AGNi_pureMIUI#1]
There was a regression somewhere between v2.9 and up. The volume down button and the power button on my kate model do not work on any release of your kernel after 2.9, both MM and N versions. I'm running it on stock CM13 official build.

No button is triggered in the logcat, so I don't have much to give you, but please let me know what debugging information you'd like.

**Comment by psndna88** [comment]
is the issue still present on v4.2 ?
