### ISSUE TITLE
sRGB got reset after screen turned on

### ISSUE THREAD

**Issue by MikuDroid** [psndna88/AGNi_pureMIUI#11]
Glad to see you back on developing AGNi for whyred! I found an issue from this kernel that has been patched at the other kernel, maybe you can merge it too? Thanks to @srfarias

https://github.com/srfarias/kernel_xiaomi_whyred/commit/6505e252455f25d8ec22ea98f5b81f978dccd1f1

**Comment by psndna88** [comment]
unable to fing commit, pls resend full link

**Comment by MikuDroid** [comment]
> unable to fing commit, pls resend full link

https://github.com/srfarias/kernel_xiaomi_whyred/commit/6505e252455f25d8ec22ea98f5b81f978dccd1f1 sorry for the derp.
