### ISSUE TITLE
Could it be upgrded with the newest zram driver？

### ISSUE THREAD

**Issue by hskks** [psndna88/AGNi_pureMIUI#17]
With these verion of the zram driver, the zram writeback could not mark the page to be idle, and it's unable to set the writeback_limit.

**Comment by psndna88** [comment]
ok ill see what can be done!

**Comment by hskks** [comment]
it is customized with the following procedure, which is named writeback.java JobSchedulerService in android framework.

Normal sequence to use idle/huge page writeback feature is as follows,

while (1) {
# mark allocated zram slot to idle
echo all >; /sys/block/zram0/idle
# leave system working for several hours
# Unless there is no access for some blocks on zram,
# they are still IDLE marked pages.

echo "idle" > /sys/block/zram0/writeback
or/and
echo "huge" > /sys/block/zram0/writeback
# write the IDLE or/and huge marked slot into backing device
# and free the memory.
}
